// Copyright 2021-present the is-valid-package-name authors. All rights reserved. MIT license.
export {
  advance,
  and,
  entries,
  first,
  flattenDeep,
  gt,
  has,
  ifElse,
  ifElseFn,
  includes,
  keys,
  length,
  lt,
  map,
  N,
  NN,
  not,
  or,
  pipe,
  props,
  startsWith,
  test,
  tryCatch,
  uniq,
} from "https://deno.land/x/fonction@v1.9.0-beta.5/mod.ts";
export {
  castString,
  everyFalse,
  gtLength,
  isArray,
  isBoolean,
  isFunction,
  isLength0,
  isLowerCase,
  isString,
  isTrimmable,
  isUndefined,
  ltLength,
  trueThen,
  trueThenAll,
} from "https://deno.land/x/is_valid@v1.0.0-beta.15/mod.ts";

export type { AnyFn } from "https://deno.land/x/fonction@v1.9.0-beta.5/mod.ts";
