// Copyright 2021-present the is-valid-package-name authors. All rights reserved. MIT license.
export {
  advance,
  and,
  entries,
  first,
  flattenDeep,
  gt,
  has,
  ifElse,
  ifElseFn,
  isArray,
  isBoolean,
  isFunction,
  isLength0,
  isString,
  isUndefined,
  keys,
  length,
  lt,
  map,
  N,
  NN,
  not,
  or,
  pipe,
  props,
  startsWith,
  trim,
  tryCatch,
  uniq,
} from "https://deno.land/x/fonction@v1.8.0-beta.5/mod.ts";
export {
  failOnTrue,
  gtLength,
  isValid,
  isValidFalse,
  ltLength,
} from "https://deno.land/x/is_valid@v1.0.0-beta.3/mod.ts";

export type { AnyFn } from "https://deno.land/x/fonction@v1.8.0-beta.5/mod.ts";
