// Copyright 2021-present the is-valid-package-name authors. All rights reserved. MIT license.

export const INVALID_LESS_THEN_2 = "Name length must be greater than 1";
export const INVALID_CORE_MODULE_NAME = "Name is standard module name";

export const INVALID_RESERVED_NAME = "Name is reserved name";
export const CORE_MODULE_NAMES = [
  "_util",
  "archive",
  "async",
  "bytes",
  "datetime",
  "encoding",
  "examples",
  "flags",
  "fmt",
  "fs",
  "hash",
  "http",
  "io",
  "log",
  "mime",
  "node",
  "assert",
  "buffer",
  "child_process",
  "cluster",
  "console",
  "constants",
  "crypto",
  "dgram",
  "dns",
  "events",
  "https",
  "http2",
  "module",
  "net",
  "os",
  "perf_hooks",
  "process",
  "querystring",
  "readline",
  "repl",
  "std",
  "stream",
  "string_decoder",
  "sys",
  "timers",
  "tls",
  "tty",
  "url",
  "util",
  "v8",
  "vm",
  "worker_threads",
  "zlib",
  "path",
  "permissions",
  "signal",
  "testing",
  "textproto",
  "uuid",
  "ws",
  "version"
];

export const RESERVED_NAMES = ["libre"];
